---

- name: Install CNTLM for enterprise proxy (local)
  tags: cntlm
  yum:
     name: /tmp/{{ cntlm_package_file | basename }}
     state: present
     disable_gpg_check: true
  when: cntlm_package_file is defined

- name: Install CNTLM for enterprise proxy (sourceforge)
  tags: cntlm
  yum:
    name: "https://downloads.sourceforge.net/project/cntlm/cntlm/cntlm%20{{ cntlm_version }}/cntlm_{{ cntlm_version_sourceforge }}.x86_64.rpm"
    state: present
  when: cntlm_package_file is not defined

- name: Ensure run directory is created on boot
  copy:
    dest: /usr/lib/tmpfiles.d/cntlm.conf
    content: |
      d /var/run/cntlm   700 cntlm cntlm

- name: Ensure run directory exists with right permissions
  file:
    group: cntlm
    mode: "g+w"
    owner: cntlm
    path: "/var/run/cntlm"
    recurse: false
    state: "directory"
